# -*- coding: utf-8 -*-
"""5.8 - Acréscimo de variáveis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bXcBLAdl-vh4D63BWeSPkUA2jvjUsqBJ

##**5.8 - Acréscimo de variáveis**
"""

import pandas as pd

df = pd.read_csv('df_OVNI_limpo.csv')

#Retirando coluna indesejada
del df['Unnamed: 0']

"""###**Dividir conteúdo da coluna Date Time em duas novas colunas. A primeira deve se chamar Sight_Date (Data) e Sight_Time (Hora)**"""

#Criando coluna no dataframe somente ano
df['Sight_Date'] = pd.to_datetime(df['Date / Time']).dt.strftime('%m/%d/%y')
#Criando coluna no dataframe somente hora
df['Sight_Time'] = pd.to_datetime(df['Date / Time']).dt.strftime('%H:%M')

"""###**Excluir coluna Date Time do DataFrame**"""

df = df.drop(['Date / Time'], axis=1)

"""###**Acrescentar uma coluna com dias da semana nomeada de Sight_Weekday**"""

df['Sight_Weekday'] = pd.to_datetime(df['Sight_Date']).dt.dayofweek

dias = {
    0: 'Segunda-Feira',
    1: 'Terça-Feira',
    2: 'Quarta-Feira',
    3: 'Quinta-Feira',
    4: 'Sexta-Feira',
    5: 'Sábado',
    6: 'Domingo'
}

df = df.replace({'Sight_Weekday': dias})

"""###**Criar coluna com dia e uma coluna de mês**"""

#Coluna para criar o dia da semana
df['Sight_Day'] = pd.to_datetime(df['Sight_Date']).dt.strftime('%d')
#Coluna para criar o mes
df['Sight_Month'] = pd.to_datetime(df['Sight_Date']).dt.strftime('%m')

"""###**Salvar o dataframe**"""

df.to_csv('df_OVNI_preparado', index = False)