# -*- coding: utf-8 -*-
"""5.2 - Script da coleta

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14iFJFDmmI-_tw4YHMBpc9m4yLc3Up373

#5.2 - Script de Coleta

##Importações
"""

import pandas as pd
import requests
from bs4 import BeautifulSoup
import time

"""##Script"""

def base_ovni(base_url):
  meses = ['01', '02','03', '04','05', '06','07', '08','09', '10','11', '12']
  final_df = pd.DataFrame()

  for ano in range(1997, 2018):    
    for mes in meses:
      req_url = base_url.format(ano, mes)      
      if ano == 1997:
        if mes not in ['10', '11', '12']:
          continue
      if ano == 2017:
        if mes in ['09','10','11', '12']:
          continue       
      req = requests.get(req_url)
      soup = BeautifulSoup(req.text, 'html.parser')
      table = soup.find_all('table')[0]
      df = pd.read_html(str(table))[0]
      final_df = pd.concat([final_df, df], ignore_index=True)
      time.sleep(1)
      
  return final_df
url = 'http://www.nuforc.org/webreports/ndxe{}{}.html'
df = base_ovni(url)

df.to_csv('ovni_data.csv')