# -*- coding: utf-8 -*-
"""5.7 - Limpeza dos dados

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DrmjjBs6D8z5hqXdXR5BZmM4YEpPeWf6

##**5.7 - Limpeza dos dados**
"""

#!pip install -U pandasql
import pandas as pd
import pandasql

"""###Chamando CSV"""

df = pd.read_csv('ovni_data.csv')

#Excluindo coluna Indesejada
del df['Unnamed: 0']

"""### Remover campos em Branco, Unknown e None"""

eliminar_campos = """
   SELECT * 
   FROM df 
   WHERE lower(City) not in ('unknown', 'none', ' ') and 
   lower(State) not in ('unknown', 'none', ' ') and 
   lower(Shape) not in ('unknown', 'none', ' ')
 """
lista_result_eliminacao = pandasql.sqldf(eliminar_campos)

"""### Manter registros que pertencem aos 51 estados dos Estados Unidos"""

estados = pd.read_csv('states.csv', sep=';')

consulta_estados_validos = '''
  SELECT lista_result_eliminacao.* 
  FROM lista_result_eliminacao, estados
  WHERE lista_result_eliminacao.State = estados.Abbreviation
'''

retorno_filtro_usa = pandasql.sqldf(consulta_estados_validos)

"""### Excluir colunas - Duration, Summary e Posted"""

excluir_col = retorno_filtro_usa.drop(['Duration', 'Summary', 'Posted'], axis=1)

"""### Mostrar registros do dataframe, no qual, os registros sejam superior à 1000 ocorrências"""

ocorrencias_shape = '''
  SELECT Shape, COUNT(Shape) as Ocorrencia 
  FROM excluir_col  
  GROUP BY Shape 
  HAVING Ocorrencia > 1000 
'''

filtro_registro = pandasql.sqldf(ocorrencias_shape)

filtro_final = '''
  SELECT excluir_col.* 
  FROM excluir_col, filtro_registro
  WHERE filtro_registro.Shape = excluir_col.Shape
'''

df_final = pandasql.sqldf(filtro_final)

df_final.to_csv('df_OVNI_limpo.csv')